name: PR Title Check

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions:
  pull-requests: read

jobs:
  pr_title_check:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
